# Generated by Django 6.0 on 2025-12-15 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="اسم الكلية"
                    ),
                ),
            ],
            options={
                "verbose_name": "الكلية",
                "verbose_name_plural": "الكليات",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم القسم")),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administration.faculty",
                        verbose_name="الكلية",
                    ),
                ),
            ],
            options={
                "verbose_name": "القسم",
                "verbose_name_plural": "الأقسام",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        unique=True,
                        verbose_name="رقم الهاتف",
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="الرقم القومي"
                    ),
                ),
                (
                    "is_user",
                    models.BooleanField(default=True, verbose_name="مستخدم عادي"),
                ),
                (
                    "is_inventory_manager",
                    models.BooleanField(default=False, verbose_name="مدير المخازن"),
                ),
                (
                    "is_inventory_employee",
                    models.BooleanField(default=False, verbose_name="موظف المخازن"),
                ),
                (
                    "is_administration_manager",
                    models.BooleanField(default=False, verbose_name="مدير الإدارة"),
                ),
                (
                    "is_administration_employee",
                    models.BooleanField(default=False, verbose_name="موظف الإدارة"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administration.department",
                        verbose_name="القسم",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administration.faculty",
                        verbose_name="الكلية",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="بيانات المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملف المستخدم",
                "verbose_name_plural": "ملفات المستخدمين",
            },
        ),
    ]
