# Generated by Django 6.0 on 2025-12-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="is_administration_employee",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_faculty_manager",
            field=models.BooleanField(default=False, verbose_name="مدير الكلية"),
        ),
    ]
