# Generated by Django 6.0 on 2026-02-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "administration",
            "0002_remove_userprofile_is_administration_employee_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="national_id",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="الرقم القومي"
            ),
        ),
    ]
