# Generated by Django 6.0 on 2026-03-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0003_alter_userprofile_national_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={
                "ordering": ["faculty", "name"],
                "verbose_name": "القسم",
                "verbose_name_plural": "الأقسام",
            },
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["faculty", "name"], name="administrat_faculty_681348_idx"
            ),
        ),
    ]
