# Generated by Django 6.0 on 2026-01-07 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "administration",
            "0002_remove_userprofile_is_administration_employee_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="اسم فئة الصنف"),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="كود الفئة"
                    ),
                ),
            ],
            options={
                "verbose_name": "فئة الصنف",
                "verbose_name_plural": "فئات الأصناف",
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="اسم الشركة"
                    ),
                ),
                (
                    "company_address",
                    models.CharField(max_length=255, verbose_name="العنوان"),
                ),
                (
                    "company_phone",
                    models.CharField(max_length=20, verbose_name="الهاتف"),
                ),
                (
                    "company_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="البريد الإلكتروني",
                    ),
                ),
                (
                    "company_notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "contact_name",
                    models.CharField(max_length=100, verbose_name="اسم المندوب"),
                ),
                (
                    "contact_address",
                    models.CharField(max_length=255, verbose_name="العنوان"),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=20, verbose_name="الهاتف"),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="البريد الإلكتروني",
                    ),
                ),
                (
                    "contact_notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
            ],
            options={
                "verbose_name": "المورد",
                "verbose_name_plural": "الموردين",
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="اسم المخزن الرئيسي"
                    ),
                ),
            ],
            options={
                "verbose_name": "المخزن الرئيسي",
                "verbose_name_plural": "المخازن الرئيسية",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="كود الصنف"
                    ),
                ),
                ("name", models.CharField(max_length=1000, verbose_name="اسم الصنف")),
                (
                    "limit_quantity",
                    models.PositiveIntegerField(verbose_name="حد الكمية"),
                ),
                (
                    "unit_fraction",
                    models.PositiveIntegerField(default=1, verbose_name="كسر الوحدة"),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("Q", "عدد"),
                            ("S", "طقم"),
                            ("K", "كيلو"),
                            ("L", "لفة"),
                            ("D", "دفتر"),
                            ("P", "قطعة"),
                            ("M", "متر"),
                            ("R", "سرنجة"),
                            ("Z", "رزمة"),
                            ("J", "زجاجة"),
                            ("B", "علبة"),
                            ("F", "فيال"),
                            ("I", "شريط"),
                            ("N", "قلم"),
                            ("E", "أنبوبة"),
                            ("X", "خرطوش"),
                            ("A", "أمبول"),
                            ("C", "كيس"),
                            ("T", "بكرة"),
                            ("U", "عبوة"),
                        ],
                        default="Q",
                        max_length=2,
                        verbose_name="وحدة القياس",
                    ),
                ),
                (
                    "spacefication",
                    models.TextField(
                        blank=True, null=True, verbose_name="مواصفات الصنف"
                    ),
                ),
                (
                    "cached_quantity",
                    models.IntegerField(
                        default=0,
                        help_text="يتم تحديثها تلقائياً عند كل عملية",
                        verbose_name="الكمية المخزنة",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.itemcategory",
                        verbose_name="فئة الصنف",
                    ),
                ),
            ],
            options={
                "verbose_name": "الصنف",
                "verbose_name_plural": "الأصناف",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ItemPriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="السعر"
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(auto_now_add=True, verbose_name="التاريخ"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.item",
                        verbose_name="الصنف",
                    ),
                ),
            ],
            options={
                "verbose_name": "تاريخ سعر الصنف",
                "verbose_name_plural": "تاريخ سعر الأصناف",
            },
        ),
        migrations.CreateModel(
            name="SubWarehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="اسم المخزن الفرعي"),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_warehouses",
                        to="administration.faculty",
                        verbose_name="الكلية",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_warehouses",
                        to="inventory.warehouse",
                        verbose_name="المخزن الرئيسي",
                    ),
                ),
            ],
            options={
                "verbose_name": "المخزن الفرعي",
                "verbose_name_plural": "المخازن الفرعية",
                "unique_together": {("name", "faculty")},
            },
        ),
        migrations.AddField(
            model_name="itemcategory",
            name="sub_warehouse",
            field=models.ManyToManyField(
                related_name="item_categories",
                to="inventory.subwarehouse",
                verbose_name="المخازن الفرعية",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="sub_warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.subwarehouse",
                verbose_name="المخزن الفرعي",
            ),
        ),
        migrations.CreateModel(
            name="ItemTransactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(max_length=50, verbose_name="رقم المستند"),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("A", "إضافة"),
                            ("D", "صرف"),
                            ("T", " نقل عهدة"),
                            ("R", "ارجاع"),
                        ],
                        default="A",
                        max_length=1,
                        verbose_name="نوع المعاملة",
                    ),
                ),
                (
                    "castody_type",
                    models.CharField(
                        choices=[
                            ("W", "عهدة مخزنية"),
                            ("P", "عهدة شخصية"),
                            ("B", "عهدة فرعية"),
                        ],
                        default="W",
                        max_length=1,
                        verbose_name="نوع العهدة",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("I", "فاتورة"),
                            ("R", "إذن ارتجاع"),
                            ("D", "إذن صرف"),
                            ("C", "كشف زيادة"),
                            ("A", "شهادة إدارية"),
                            ("B", "كشف عجز"),
                            ("S", "سند خصم أصناف فاقدة أو تالفة"),
                            ("M", "محضر بيع"),
                            ("T", "طلب تشغيل"),
                            ("G", "إهداءات ليست النشاط الرئيسي للجهة"),
                            ("E", "طلب ارتجاع أصناف"),
                            ("F", "نقل عهدة"),
                        ],
                        default="I",
                        max_length=1,
                        verbose_name="نوع المستند",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "approval_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الموافقة"
                    ),
                ),
                ("deleted", models.BooleanField(default=False, verbose_name="محذوف")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الحذف"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ التعديل"
                    ),
                ),
                (
                    "approval_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approved_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المشرف",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حُذف بواسطة",
                    ),
                ),
                (
                    "from_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_transactions",
                        to="administration.department",
                        verbose_name="من القسم",
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="من المستخدم",
                    ),
                ),
                (
                    "inventory_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="موظف المخزن",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="عُدل بواسطة",
                    ),
                ),
                (
                    "to_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_transactions",
                        to="administration.department",
                        verbose_name="إلى القسم",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="إلى المستخدم",
                    ),
                ),
                (
                    "from_sub_warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_sub_transactions",
                        to="inventory.subwarehouse",
                        verbose_name="من المخزن الفرعي",
                    ),
                ),
                (
                    "to_sub_warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_sub_transactions",
                        to="inventory.subwarehouse",
                        verbose_name="إلى المخزن الفرعي",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="inventory.supplier",
                        verbose_name="المورد",
                    ),
                ),
                (
                    "from_warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_main_transactions",
                        to="inventory.warehouse",
                        verbose_name="من المخزن الرئيسي",
                    ),
                ),
                (
                    "to_warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_main_transactions",
                        to="inventory.warehouse",
                        verbose_name="إلى المخزن الرئيسي",
                    ),
                ),
            ],
            options={
                "verbose_name": "السند",
                "verbose_name_plural": "السندات",
            },
        ),
        migrations.CreateModel(
            name="TransactionAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("C", "إنشاء"),
                            ("U", "تعديل"),
                            ("D", "حذف"),
                            ("R", "استعادة"),
                        ],
                        max_length=1,
                        verbose_name="نوع الإجراء",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإجراء"
                    ),
                ),
                (
                    "transaction_snapshot",
                    models.JSONField(blank=True, null=True, verbose_name="لقطة السند"),
                ),
                (
                    "changed_fields",
                    models.JSONField(
                        blank=True, null=True, verbose_name="الحقول المعدلة"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="عنوان IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, null=True, verbose_name="وكيل المستخدم"
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transaction_audits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="نفّذ بواسطة",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="inventory.itemtransactions",
                        verbose_name="السند",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تدقيق المعاملة",
                "verbose_name_plural": "سجلات تدقيق المعاملات",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="item",
            name="warehouse",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.warehouse",
                verbose_name="المخزن الرئيسي",
            ),
        ),
        migrations.CreateModel(
            name="ItemTransactionDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("N", "جديد"),
                            ("U", "مستعمل"),
                            ("R", "قابل للاصلاح"),
                            ("D", "كهنة وخردة"),
                        ],
                        default="N",
                        max_length=1,
                        verbose_name="حالة الصنف",
                    ),
                ),
                (
                    "order_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="الكمية المطلوبة"
                    ),
                ),
                (
                    "approved_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="الكمية المنصرفة"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.item",
                        verbose_name="الصنف",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.itemtransactions",
                        verbose_name="المعاملة",
                    ),
                ),
            ],
            options={
                "verbose_name": "تفاصيل معاملة الصنف",
                "verbose_name_plural": "تفاصيل معاملات الأصناف",
                "indexes": [
                    models.Index(
                        fields=["item", "transaction"],
                        name="inventory_i_item_id_833ff9_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="itemtransactions",
            index=models.Index(
                fields=["from_warehouse", "created_at"],
                name="inventory_i_from_wa_8857a8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="itemtransactions",
            index=models.Index(
                fields=["to_warehouse", "created_at"],
                name="inventory_i_to_ware_4555bc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="itemtransactions",
            index=models.Index(
                fields=["from_sub_warehouse", "created_at"],
                name="inventory_i_from_su_d9f2bf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="itemtransactions",
            index=models.Index(
                fields=["to_sub_warehouse", "created_at"],
                name="inventory_i_to_sub__9f7386_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["sub_warehouse", "category"],
                name="inventory_i_sub_war_96e036_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["sub_warehouse", "name"], name="inventory_i_sub_war_0b9831_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["warehouse", "category"], name="inventory_i_warehou_be0d8c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["cached_quantity"], name="inventory_i_cached__ca1283_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="item",
            unique_together={("name", "sub_warehouse")},
        ),
    ]
