# Generated by Django 6.0 on 2026-01-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itemtransactions",
            options={
                "permissions": [
                    ("approve_transaction", "يمكنه اعتماد السندات"),
                    ("reject_transaction", "يمكنه رفض السندات"),
                ],
                "verbose_name": "السند",
                "verbose_name_plural": "السندات",
            },
        ),
        migrations.AddField(
            model_name="itemtransactions",
            name="approval_notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="ملاحظات الاعتماد"
            ),
        ),
        migrations.AddField(
            model_name="itemtransactions",
            name="approval_status",
            field=models.CharField(
                choices=[("P", "قيد الانتظار"), ("A", "معتمد"), ("R", "مرفوض")],
                default="P",
                max_length=1,
                verbose_name="حالة الاعتماد",
            ),
        ),
        migrations.AlterField(
            model_name="itemtransactions",
            name="approval_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الاعتماد"
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                condition=models.Q(("cached_quantity__gte", 0)),
                name="non_negative_quantity",
            ),
        ),
    ]
