# Generated by Django 6.0 on 2026-01-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_alter_itemtransactions_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("C", "إنشاء"),
                    ("U", "تعديل"),
                    ("D", "حذف"),
                    ("S", "استعادة"),
                    ("A", "اعتماد"),
                    ("R", "رفض"),
                    ("V", "عرض"),
                ],
                max_length=1,
                verbose_name="نوع الإجراء",
            ),
        ),
    ]
