# Generated by Django 6.0 on 2026-01-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_alter_transactionauditlog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="item_images/",
                verbose_name="صورة الصنف",
            ),
        ),
    ]
