# Generated by Django 6.0 on 2026-01-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_item_item_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemtransactiondetails",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="السعر"
            ),
        ),
    ]
