# Generated by Django 6.0 on 2026-01-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_itemtransactiondetails_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemtransactiondetails",
            name="order_quantity",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="الكمية المطلوبة"
            ),
        ),
    ]
