# Generated by Django 6.0 on 2026-01-18 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "administration",
            "0002_remove_userprofile_is_administration_employee_and_more",
        ),
        ("inventory", "0006_alter_itemtransactiondetails_order_quantity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="last_quantity_update",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="آخر تحديث للكمية"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="cached_quantity",
            field=models.IntegerField(
                default=0,
                help_text="تُحدَّث تلقائياً عند اعتماد السندات فقط",
                verbose_name="الكمية المخزنة",
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["last_quantity_update"], name="inventory_i_last_qu_5072e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="itemtransactions",
            index=models.Index(
                fields=["approval_status", "created_at"],
                name="inventory_i_approva_97f757_idx",
            ),
        ),
    ]
