# Generated by Django 6.0 on 2026-02-25 21:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0003_alter_userprofile_national_id"),
        (
            "inventory",
            "0007_item_last_quantity_update_alter_item_cached_quantity_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="subwarehouse",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="كود مختصر للمخزن يُستخدم في أرقام المستندات (اختياري)",
                max_length=10,
                null=True,
                verbose_name="كود المخزن",
            ),
        ),
        migrations.AlterField(
            model_name="itemtransactions",
            name="document_number",
            field=models.CharField(
                blank=True, editable=False, max_length=50, verbose_name="رقم المستند"
            ),
        ),
        migrations.AddIndex(
            model_name="itemtransactions",
            index=models.Index(
                fields=["transaction_type", "from_sub_warehouse", "document_number"],
                name="inventory_i_transac_efd694_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subwarehouse",
            index=models.Index(fields=["code"], name="inventory_s_code_6009d8_idx"),
        ),
        migrations.AddConstraint(
            model_name="itemtransactions",
            constraint=models.UniqueConstraint(
                condition=models.Q(("transaction_type__in", ["D", "T"])),
                fields=("transaction_type", "from_sub_warehouse", "document_number"),
                name="unique_doc_from_sub_warehouse",
            ),
        ),
    ]
