# Generated by Django 6.0 on 2026-02-25 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0003_alter_userprofile_national_id"),
        ("inventory", "0008_subwarehouse_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="itemtransactions",
            name="is_reversed",
            field=models.BooleanField(
                default=False, help_text="هل تم عكس هذا السند؟", verbose_name="تم عكسه"
            ),
        ),
        migrations.AddField(
            model_name="itemtransactions",
            name="reversed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ العكس"
            ),
        ),
        migrations.AddField(
            model_name="itemtransactions",
            name="reversed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reversed_transactions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="عكس بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="itemtransactions",
            name="reversed_transaction",
            field=models.ForeignKey(
                blank=True,
                help_text="السند الذي تم إنشاؤه لعكس هذا السند",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="original_transaction",
                to="inventory.itemtransactions",
                verbose_name="سند العكس",
            ),
        ),
        migrations.AddIndex(
            model_name="itemtransactions",
            index=models.Index(
                fields=["is_reversed"], name="inventory_i_is_reve_5c0d49_idx"
            ),
        ),
    ]
