# Generated by Django 6.0 on 2026-03-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0009_itemtransactions_is_reversed_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itemtransactiondetails",
            options={
                "ordering": ["transaction__to_user"],
                "verbose_name": "تفاصيل معاملة الصنف",
                "verbose_name_plural": "تفاصيل معاملات الأصناف",
            },
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["sub_warehouse", "cached_quantity"],
                name="inventory_i_sub_war_5b657b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["cached_quantity", "limit_quantity"],
                name="inventory_i_cached__a45423_idx",
            ),
        ),
    ]
