# Generated by Django 6.0 on 2026-03-04 23:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0010_alter_itemtransactiondetails_options_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="item",
            name="inventory_i_warehou_be0d8c_idx",
        ),
    ]
