# Generated by Django 6.0 on 2026-03-09 19:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0011_remove_item_inventory_i_warehou_be0d8c_idx"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itemtransactiondetails",
            options={
                "ordering": ["id"],
                "verbose_name": "تفاصيل معاملة الصنف",
                "verbose_name_plural": "تفاصيل معاملات الأصناف",
            },
        ),
    ]
