# Generated by Django 6.0 on 2026-03-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0012_alter_itemtransactiondetails_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemtransactions",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("P", "قيد الانتظار"),
                    ("A", "معتمد"),
                    ("R", "مرفوض"),
                    ("D", "محذوف"),
                ],
                default="P",
                max_length=1,
                verbose_name="حالة الاعتماد",
            ),
        ),
    ]
