# Generated by Django 6.0 on 2026-03-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0013_alter_itemtransactions_approval_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="يمكن تعديله، يجب أن يكون فريداً",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="كود الصنف",
            ),
        ),
    ]
