# Generated by Django 6.0 on 2026-04-05 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0014_alter_item_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="cached_quantity",
            field=models.IntegerField(
                default=0,
                help_text="تُحدَّث تلقائياً عند اعتماد السندات (للمخزن الأصلي فقط)",
                verbose_name="الكمية المخزنة",
            ),
        ),
        migrations.AlterField(
            model_name="itemcategory",
            name="sub_warehouse",
            field=models.ManyToManyField(
                blank=True,
                related_name="item_categories",
                to="inventory.subwarehouse",
                verbose_name="المخازن الفرعية",
            ),
        ),
        migrations.AlterField(
            model_name="itemtransactions",
            name="reversed_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="original_transaction",
                to="inventory.itemtransactions",
                verbose_name="سند العكس",
            ),
        ),
        migrations.CreateModel(
            name="FacultyItemStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cached_quantity",
                    models.IntegerField(default=0, verbose_name="الكمية المخزنة"),
                ),
                (
                    "limit_quantity",
                    models.PositiveIntegerField(default=0, verbose_name="حد الكمية"),
                ),
                (
                    "last_quantity_update",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر تحديث للكمية"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faculty_stocks",
                        to="inventory.item",
                        verbose_name="الصنف",
                    ),
                ),
                (
                    "sub_warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_stocks",
                        to="inventory.subwarehouse",
                        verbose_name="المخزن الفرعي",
                    ),
                ),
            ],
            options={
                "verbose_name": "مخزون الكلية",
                "verbose_name_plural": "مخزون الكليات",
                "indexes": [
                    models.Index(
                        fields=["sub_warehouse", "cached_quantity"],
                        name="inventory_f_sub_war_b9c745_idx",
                    ),
                    models.Index(
                        fields=["item", "sub_warehouse"],
                        name="inventory_f_item_id_f9a3ef_idx",
                    ),
                    models.Index(
                        fields=["cached_quantity", "limit_quantity"],
                        name="inventory_f_cached__0307bb_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("cached_quantity__gte", 0)),
                        name="non_negative_faculty_stock_quantity",
                    )
                ],
                "unique_together": {("item", "sub_warehouse")},
            },
        ),
    ]
