# Generated by Django 6.0 on 2026-04-05 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0004_alter_department_options_and_more"),
        ("inventory", "0015_alter_item_cached_quantity_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={
                "ordering": ["name"],
                "verbose_name": "الصنف",
                "verbose_name_plural": "الأصناف",
            },
        ),
        migrations.AlterModelOptions(
            name="itemcategory",
            options={
                "ordering": ["name"],
                "verbose_name": "فئة الصنف",
                "verbose_name_plural": "فئات الأصناف",
            },
        ),
        migrations.AlterModelOptions(
            name="itempricehistory",
            options={
                "ordering": ["-date"],
                "verbose_name": "تاريخ سعر الصنف",
                "verbose_name_plural": "تاريخ سعر الأصناف",
            },
        ),
        migrations.AlterModelOptions(
            name="supplier",
            options={
                "ordering": ["name"],
                "verbose_name": "المورد",
                "verbose_name_plural": "الموردين",
            },
        ),
        migrations.AlterModelOptions(
            name="warehouse",
            options={
                "ordering": ["name"],
                "verbose_name": "المخزن الرئيسي",
                "verbose_name_plural": "المخازن الرئيسية",
            },
        ),
        migrations.RemoveIndex(
            model_name="item",
            name="inventory_i_sub_war_96e036_idx",
        ),
        migrations.RemoveIndex(
            model_name="item",
            name="inventory_i_sub_war_0b9831_idx",
        ),
        migrations.RemoveIndex(
            model_name="item",
            name="inventory_i_last_qu_5072e0_idx",
        ),
        migrations.RemoveIndex(
            model_name="item",
            name="inventory_i_sub_war_5b657b_idx",
        ),
        migrations.RemoveIndex(
            model_name="item",
            name="inventory_i_cached__a45423_idx",
        ),
        migrations.AlterUniqueTogether(
            name="item",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="itemcategory",
            name="sub_warehouse",
        ),
        migrations.AlterUniqueTogether(
            name="subwarehouse",
            unique_together={("name",)},
        ),
        migrations.AddField(
            model_name="itemtransactions",
            name="faculty",
            field=models.ForeignKey(
                default=1,
                help_text="الكلية المالكة لهذا السند",
                on_delete=django.db.models.deletion.CASCADE,
                to="administration.faculty",
                verbose_name="الكلية",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(
                help_text="يجب أن يكون اسم الصنف فريداً عالمياً",
                max_length=1000,
                unique=True,
                verbose_name="اسم الصنف",
            ),
        ),
        migrations.AlterField(
            model_name="itemtransactions",
            name="reversed_transaction",
            field=models.ForeignKey(
                blank=True,
                help_text="السند الذي تم إنشاؤه لعكس هذا السند",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="original_transaction",
                to="inventory.itemtransactions",
                verbose_name="سند العكس",
            ),
        ),
        migrations.AlterField(
            model_name="itemtransactions",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("A", "إضافة"),
                    ("D", "صرف"),
                    ("T", "نقل عهدة"),
                    ("R", "ارجاع"),
                ],
                default="A",
                max_length=1,
                verbose_name="نوع المعاملة",
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["category"], name="inventory_i_categor_dcc1fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["name"], name="inventory_i_name_637656_idx"),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["code"], name="inventory_i_code_0aa0a4_idx"),
        ),
        migrations.AddIndex(
            model_name="itempricehistory",
            index=models.Index(
                fields=["item", "-date"], name="inventory_i_item_id_56d69a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="itemtransactions",
            index=models.Index(
                fields=["faculty", "created_at"], name="inventory_i_faculty_bee323_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="itemtransactions",
            index=models.Index(
                fields=["faculty", "approval_status"],
                name="inventory_i_faculty_afbcd8_idx",
            ),
        ),
        migrations.RemoveField(
            model_name="subwarehouse",
            name="faculty",
        ),
    ]
