# Generated by Django 6.0 on 2026-04-05 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0004_alter_department_options_and_more"),
        ("inventory", "0018_faculty_item_stock_faculty"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facultyitemstock",
            options={
                "verbose_name": "Ù…Ø®Ø²ÙˆÙ† Ø§Ù„ÙƒÙ„ÙŠØ©",
                "verbose_name_plural": "Ù…Ø®Ø²ÙˆÙ† Ø§Ù„ÙƒÙ„ÙŠØ§Øª",
            },
        ),
        migrations.AlterModelOptions(
            name="supplier",
            options={"verbose_name": "المورد", "verbose_name_plural": "الموردين"},
        ),
        migrations.RemoveConstraint(
            model_name="facultyitemstock",
            name="non_negative_faculty_stock_quantity",
        ),
        migrations.RemoveIndex(
            model_name="facultyitemstock",
            name="inventory_f_sub_war_b9c745_idx",
        ),
        migrations.RemoveIndex(
            model_name="facultyitemstock",
            name="inventory_f_item_id_f9a3ef_idx",
        ),
        migrations.RemoveIndex(
            model_name="item",
            name="inventory_i_categor_dcc1fb_idx",
        ),
        migrations.RemoveIndex(
            model_name="item",
            name="inventory_i_name_637656_idx",
        ),
        migrations.RemoveIndex(
            model_name="item",
            name="inventory_i_code_0aa0a4_idx",
        ),
        migrations.AddField(
            model_name="itemcategory",
            name="sub_warehouse",
            field=models.ManyToManyField(
                related_name="item_categories",
                to="inventory.subwarehouse",
                verbose_name="المخازن الفرعية",
            ),
        ),
        migrations.AlterField(
            model_name="facultyitemstock",
            name="cached_quantity",
            field=models.IntegerField(
                default=0, verbose_name="Ø§Ù„ÙƒÙ…ÙŠØ© Ø§Ù„Ù…Ø®Ø²Ù†Ø©"
            ),
        ),
        migrations.AlterField(
            model_name="facultyitemstock",
            name="faculty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_stocks",
                to="administration.faculty",
                verbose_name="Ø§Ù„ÙƒÙ„ÙŠØ©",
            ),
        ),
        migrations.AlterField(
            model_name="facultyitemstock",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faculty_stocks",
                to="inventory.item",
                verbose_name="Ø§Ù„ØµÙ†Ù\x81",
            ),
        ),
        migrations.AlterField(
            model_name="facultyitemstock",
            name="last_quantity_update",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Ø¢Ø®Ø± ØªØ\xadØ¯ÙŠØ« Ù„Ù„ÙƒÙ…ÙŠØ©"
            ),
        ),
        migrations.AlterField(
            model_name="facultyitemstock",
            name="limit_quantity",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Ø\xadØ¯ Ø§Ù„ÙƒÙ…ÙŠØ©"
            ),
        ),
        migrations.AlterField(
            model_name="facultyitemstock",
            name="sub_warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_stocks",
                to="inventory.subwarehouse",
                verbose_name="Ø§Ù„Ù…Ø®Ø²Ù† Ø§Ù„Ù\x81Ø±Ø¹ÙŠ",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="cached_quantity",
            field=models.IntegerField(
                default=0,
                help_text="تُحدَّث تلقائياً عند اعتماد السندات فقط",
                verbose_name="الكمية المخزنة",
            ),
        ),
        migrations.AddIndex(
            model_name="facultyitemstock",
            index=models.Index(
                fields=["faculty", "sub_warehouse", "cached_quantity"],
                name="inventory_f_faculty_7403fe_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="facultyitemstock",
            index=models.Index(
                fields=["faculty", "item", "sub_warehouse"],
                name="inventory_f_faculty_223c1a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["sub_warehouse", "category"],
                name="inventory_i_sub_war_96e036_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["sub_warehouse", "name"], name="inventory_i_sub_war_0b9831_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["last_quantity_update"], name="inventory_i_last_qu_5072e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["sub_warehouse", "cached_quantity"],
                name="inventory_i_sub_war_5b657b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["cached_quantity", "limit_quantity"],
                name="inventory_i_cached__a45423_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="facultyitemstock",
            constraint=models.CheckConstraint(
                condition=models.Q(("cached_quantity__gte", 0)),
                name="non_negative_faculty_stock_quantity_v2",
            ),
        ),
    ]
