# Generated by Django 6.0 on 2026-04-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0005_userprofile_nullable_faculty_department"),
        ("inventory", "0019_alter_facultyitemstock_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facultyitemstock",
            options={
                "verbose_name": "مخزون الكلية",
                "verbose_name_plural": "مخزون الكليات",
            },
        ),
        migrations.AddIndex(
            model_name="facultyitemstock",
            index=models.Index(
                fields=["faculty", "sub_warehouse", "item"],
                name="inventory_f_faculty_b030d7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="itemcategory",
            index=models.Index(fields=["name"], name="inventory_i_name_9b7fa9_idx"),
        ),
    ]
