# Generated by Django 6.0 on 2026-04-09 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0020_alter_facultyitemstock_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemcategory",
            name="sub_warehouse",
        ),
        migrations.AddField(
            model_name="itemcategory",
            name="sub_warehouse",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_categories",
                to="inventory.subwarehouse",
                verbose_name="المخازن الفرعية",
            ),
            preserve_default=False,
        ),
    ]
