# Generated by Django 6.0 on 2026-04-09 21:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0021_remove_itemcategory_sub_warehouse_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemcategory",
            name="code",
        ),
    ]
