# Generated by Django 6.0 on 2026-04-09 22:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0023_item_created_at_item_created_by_item_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="item",
            name="inventory_i_sub_war_96e036_idx",
        ),
        migrations.RemoveIndex(
            model_name="item",
            name="inventory_i_sub_war_0b9831_idx",
        ),
        migrations.RemoveIndex(
            model_name="item",
            name="inventory_i_sub_war_5b657b_idx",
        ),
        migrations.RemoveField(
            model_name="item",
            name="sub_warehouse",
        ),
        migrations.RemoveField(
            model_name="item",
            name="warehouse",
        ),
    ]
