# Generated by Django 6.0 on 2026-04-13 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0005_userprofile_nullable_faculty_department"),
        ("inventory", "0024_remove_item_inventory_i_sub_war_96e036_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facultyitemstock",
            name="cached_quantity",
            field=models.IntegerField(default=0, verbose_name="الكمية المخزنة"),
        ),
        migrations.AlterField(
            model_name="facultyitemstock",
            name="faculty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_stocks",
                to="administration.faculty",
                verbose_name="الكلية",
            ),
        ),
        migrations.AlterField(
            model_name="facultyitemstock",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faculty_stocks",
                to="inventory.item",
                verbose_name="الصنف",
            ),
        ),
        migrations.AlterField(
            model_name="facultyitemstock",
            name="last_quantity_update",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="آخر تحديث للكمية"
            ),
        ),
        migrations.AlterField(
            model_name="facultyitemstock",
            name="limit_quantity",
            field=models.PositiveIntegerField(default=0, verbose_name="حد الكمية"),
        ),
        migrations.AlterField(
            model_name="facultyitemstock",
            name="sub_warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_stocks",
                to="inventory.subwarehouse",
                verbose_name="المخزن الفرعي",
            ),
        ),
    ]
