# Generated by Django 6.0 on 2026-04-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0025_alter_facultyitemstock_cached_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="unit",
            field=models.CharField(
                choices=[
                    ("Q", "عدد"),
                    ("S", "طقم"),
                    ("K", "كيلو"),
                    ("L", "لفة"),
                    ("D", "دفتر"),
                    ("P", "قطعة"),
                    ("M", "متر"),
                    ("R", "سرنجة"),
                    ("Z", "رزمة"),
                    ("J", "زجاجة"),
                    ("B", "علبة"),
                    ("F", "فيال"),
                    ("I", "شريط"),
                    ("N", "قلم"),
                    ("E", "أنبوبة"),
                    ("X", "خرطوش"),
                    ("A", "أمبول"),
                    ("C", "كيس"),
                    ("T", "بكرة"),
                    ("U", "عبوة"),
                    ("G", "شوال"),
                    ("O", "كرتونة"),
                    ("Y", "كيس"),
                ],
                default="Q",
                max_length=2,
                verbose_name="وحدة القياس",
            ),
        ),
    ]
