# Generated by Django 6.0 on 2026-05-06 18:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_systemsettings_inventoryyear'),
        ('inventory', '0028_itemtransactions_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='itemtransactions',
            index=models.Index(fields=['year', 'faculty', '-created_at'], name='inventory_i_year_id_671d51_idx'),
        ),
        migrations.AddIndex(
            model_name='itemtransactions',
            index=models.Index(fields=['faculty', 'approval_status', '-created_at'], name='inventory_i_faculty_439af4_idx'),
        ),
        migrations.AddIndex(
            model_name='itemtransactions',
            index=models.Index(fields=['created_by', 'faculty', '-created_at'], name='inventory_i_created_daf91d_idx'),
        ),
        migrations.AddIndex(
            model_name='itemtransactions',
            index=models.Index(fields=['document_number'], name='inventory_i_documen_945993_idx'),
        ),
        migrations.AddIndex(
            model_name='itemtransactions',
            index=models.Index(fields=['notes'], name='idx_notes_search'),
        ),
    ]
